# Site settings
name: Laura Ann Busch
title: Laura Ann Busch | Ph.D Astronomy/Astrophysics
description: Astrophysicist researching star formation and astrochemistry, in particular, the molecular complexity of protostellar environments.
url: "https://lbusch-24.github.io"
baseurl: ""
email: lbusch@mpe.mpg.de
resume: https://lbusch-24.github.io/CV.pdf
social:
  - title: email
    url: mailto:lbusch@mpe.mpg.de
  - title: github
    url: https://github.com/lbusch-24

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
